Domain : 알고리즘 CRUD 및 예외처리
MogakCote/mogak-codingtest pull request #43
Opened 2024-08-30 13:27 UTC by LeeJaejun98

## 🚀 연관된 이슈

> 다음과 같이 이슈를 관리합니다.  
> - resolve: #17 

## ✨ 작업 내용

> 알고리즘 CRUD 생성

## 💬 리뷰 요구사항(선택)

> 여기서도 권한 문제가 생깁니다... 확인 부탁드립니다.

2024-09-01 18:14 UTC, OhHaneol requested changes
고생하셨습니다 재준 님! 몇 가지 수정사항에 대한 코멘트를 남겼습니다. 확인하고 수정 부탁드려요😄
그 전에 기존 커밋 기록이 꼬인 것 부터 한 번 살펴봐도 좋을 것 같습니다!

2024-09-01 18:14 UTC, ohahsis commented on src/main/java/com/ormi/mogakcote/algorithm/domain/Algorithm.java
> +        this.algorithmId = algorithmId;
Id 를 수정하는 이유가 혹시 있을까요?

2024-09-01 18:14 UTC, ohahsis commented on src/main/java/com/ormi/mogakcote/algorithm/application/AlgorithmService.java
> +            Long id, AlgorithmRequest request
id -> userId 로 이름 변경하는 게 어떨까요?

2024-09-01 18:14 UTC, ohahsis commented on src/main/java/com/ormi/mogakcote/algorithm/application/AlgorithmService.java
> +        Algorithm algorithm = buildAlgorithm(request, id);
해당 메서드에서 id 필드가 쓰이고 있지 않다면 없애는 게 좋을 것 같습니다!

2024-09-01 18:14 UTC, ohahsis commented on src/main/java/com/ormi/mogakcote/algorithm/application/AlgorithmService.java
> +        throwsIfAlgorithmNotExist(algorithmId);
id 를 확인하는 방법은 좋은 것 같습니다😊
다만 해당 확인 메서드가
- getAlgorithmById 와 함께 쓰인다는 점
- 둘 다 id 를 이용하여 알고리즘을 검색했을 때 없으면 `ALGORITHM_NOT_FOUND_ERROR ` 를 발생시킨다는 점

이 두 가지를 고려하면 두 메서드를 합치는 것이 좋을 것 같아요.
제 제안은 throwsIfAlgorithmNotExist 를 삭제하되 getAlgorithmById 메서드의 이름을 getAlgorithmOrThrowIfNotExist 와 같이 수정하는 것입니다!

2024-09-01 18:14 UTC, OhHaneol commented on src/main/java/com/ormi/mogakcote/algorithm/dto/request/AlgorithmRequest.java
> +    private Integer algorithmId;
request 로 algorithmId 를 받아 사용되는 곳이 혹시 있을까요? 제 생각에는 name 만 있어도 충분할 것 같아요!

2024-09-01 18:14 UTC, OhHaneol commented on src/main/java/com/ormi/mogakcote/algorithm/infrastructure/AlgorithmRepository.java
> +    Algorithm save(Algorithm algorithm);
save 는 jpa 에서 기본으로 제공하는 기능이라서, 따로 명시하지 않아도 아마 오류 없이 잘 동작할 것 같습니다!
한 번 삭제해보시고 정상 작동하는 지 확인해주신 다음 변경하면 좋을 것 같아요 🙌

2024-09-01 18:14 UTC, OhHaneol commented on src/main/java/com/ormi/mogakcote/algorithm/presentation/AlgorithmController.java
> +            @PathVariable Integer algorithmId,
PathVariable 은 name 설정을 해주지 않을 경우 가끔 문제가 발생하기 때문에, (name = "algorithmId") 를 해주시면 좋을 것 같아요😊

2024-09-01 18:14 UTC, OhHaneol commented on src/main/java/com/ormi/mogakcote/algorithm/domain/Algorithm.java
> +    private Integer algorithmId;
Integer -> Long 으로 타입 바꿔주세요~! 다른 곳에도 int 형으로 쓰인 곳이 있다면 적용 부탁드립니다!

2024-09-01 18:14 UTC, OhHaneol commented on src/main/java/com/ormi/mogakcote/algorithm/presentation/AlgorithmController.java
> +            @PathVariable Integer algorithmId
마찬가지로 name 설정 부탁드려요 ㅎㅎ

2024-09-01 18:14 UTC, OhHaneol commented on src/main/java/com/ormi/mogakcote/exception/dto/ErrorType.java
> +    SYSTEM_USER_NOT_FOUND_ERROR(HttpStatus.NOT_FOUND, "시스템 유저를 찾을 수 없습니다."),
이거 문제가 있었는데 수정 감사합니다😄

2024-09-01 18:14 UTC, OhHaneol commented on src/main/java/com/ormi/mogakcote/comment/application/SystemCommentService.java
제가 기존에 develop 에 merge 한 커밋 기록들이 같이 왔네요 😳
pull 하는 과정에서 꼬인 것 같은데..! 한 번 고치는 것 시도해보고 안 되면 이대로 올려도 될 것 같습니다!

2024-09-02 00:51 UTC, LeeJaejun98 commented on src/main/java/com/ormi/mogakcote/algorithm/presentation/AlgorithmController.java
> +            @PathVariable Integer algorithmId
여기서 말씀하시는 name설정이 뭘까요?

2024-09-02 01:21 UTC, OhHaneol commented on src/main/java/com/ormi/mogakcote/algorithm/presentation/AlgorithmController.java
> +            @PathVariable Integer algorithmId
> PathVariable 은 name 설정을 해주지 않을 경우 가끔 문제가 발생하기 때문에, (name = "algorithmId") 를 해주시면 좋을 것 같아요😊

위에 단 코멘트랑 같은 말이었습니다! PathVariable 에 모두 적용해주세요!

2024-09-02 05:56 UTC, OhHaneol requested changes

2024-09-02 05:56 UTC, OhHaneol commented on src/main/java/com/ormi/mogakcote/problem/application/AlgorithmService.java
> +    private Algorithm buildAlgorithm(AlgorithmRequest request, Long algorithmId) {
해당 메서드가 사용되는 곳에서는 userId 가 주입되고 있습니다. 아마 request 에 id 필드를 추가하면 될 것 같은데, 확인해주세요~!

2024-09-02 06:09 UTC, LeeJaejun98 commented on src/main/java/com/ormi/mogakcote/algorithm/presentation/AlgorithmController.java
> +            @PathVariable Integer algorithmId
pathvariable은 전부다 확인 했습니다.

2024-09-02 06:10 UTC, LeeJaejun98 commented on src/main/java/com/ormi/mogakcote/algorithm/domain/Algorithm.java
> +    private Integer algorithmId;
Long 타입으로 변환 끝났습니다.

2024-09-02 06:10 UTC, LeeJaejun98 commented on src/main/java/com/ormi/mogakcote/algorithm/infrastructure/AlgorithmRepository.java
> +    Algorithm save(Algorithm algorithm);
삭제 완료 했습니다.

2024-09-02 06:10 UTC, LeeJaejun98 commented on src/main/java/com/ormi/mogakcote/algorithm/dto/request/AlgorithmRequest.java
> +    private Integer algorithmId;
name으로만 변경 완료 했습니다

2024-09-02 06:11 UTC, LeeJaejun98 commented on src/main/java/com/ormi/mogakcote/algorithm/application/AlgorithmService.java
> +        Algorithm algorithm = buildAlgorithm(request, id);
이 부분이 애매합니다... 추후 코드 변경 있을수도 있어서 남겨놨습니다...

2024-09-02 06:13 UTC, LeeJaejun98 commented on src/main/java/com/ormi/mogakcote/algorithm/domain/Algorithm.java
> +        this.algorithmId = algorithmId;
name만 변경하도록 고쳤습니다.

2024-09-02 06:23 UTC, OhHaneol requested changes

2024-09-02 06:23 UTC, OhHaneol commented on src/main/java/com/ormi/mogakcote/exception/dto/ErrorType.java
> -    NOTICE_NOT_FOUND_ERROR(HttpStatus.NOT_FOUND, "공지사항을 찾을 수 없습니다."),
사라진 예외 다시 추가 부탁드려요!

2024-09-02 06:32 UTC, LeeJaejun98 commented on src/main/java/com/ormi/mogakcote/exception/dto/ErrorType.java
> -    NOTICE_NOT_FOUND_ERROR(HttpStatus.NOT_FOUND, "공지사항을 찾을 수 없습니다."),
notice 예외 말씀 하시는거죠? 이거는 있습니다

2024-09-02 06:33 UTC, LeeJaejun98 commented on src/main/java/com/ormi/mogakcote/problem/application/AlgorithmService.java
> +    private Algorithm buildAlgorithm(AlgorithmRequest request, Long algorithmId) {
userId말고 algorithmId를 받아와야된다는 말씀이신거죠? 그럼 requeset에 Long algorithmId 만들어서 get으로 가지고 오라는 말씀이신가요?

2024-09-02 07:18 UTC, OhHaneol approved these changes
고생하셨어요 😊🙌

2024-09-02 07:19 UTC, merged